### ISSUE TITLE
Korruption og diktatur

### ISSUE THREAD

**Issue by Tobi1790** [slotshaven-digitek-2018/discussion-board#3]
Simon og Lucas er owners, jeg synes deres tid er kommet til at de skal gå ned fra deres position og tillade en ny Præsident og Vice Præsident. Jeg stemmer for Noah og Bjarke.
![udklip](https://user-images.githubusercontent.com/45455484/49219118-9eefd680-f3d2-11e8-9c34-8df15ef223a3.PNG)

**Comment by simonjelstrup** [comment]
stemmer måske
